export const BACK_END_URI = process.env.BACK_END_URI;
export const OPTIONS_PROGRAMMING_LANGUAGES = [
  "HTML",
  "CSS",
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "PHP",
  "Ruby",
  "Swift",
  "TypeScript",
  "Kotlin",
  "Go",
  "Rust",
  "Perl",
  "Scala",
  "Haskell",
  "R",
  "SCSS",
];

export const OPTIONS_SUITABLE_JOBS = [
  "Front-end Web Development",
  "Back-end Web Development",
  "Fullstack Web Development",
  "Fullstack Mobile",
  "AI Engineering",
  "Software Development",
  "Data Science",
  "Cybersecurity",
  "Cloud Computing",
  "Artificial Intelligence",
  "Mobile App Development",
  "Network Engineering",
  "Database Administration",
  "DevOps",
  "IT Project Management",
  "Machine Learning",
  "Blockchain Development",
  "Game Development",
];
