import { ThemeRegistry } from "@/config/theme";
import NextAuthProvider from "@/providers/NextAuthProvider";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const metadata: Metadata = {
  title: "EST Edu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <NextAuthProvider>{children}</NextAuthProvider>
        </ThemeRegistry>
        <ToastContainer />
      </body>
    </html>
  );
}
